/*
 * Text2Motion API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Text2MotionClientAPI.Api;
using Text2MotionClientAPI.Model;
using Text2MotionClientAPI.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace Text2MotionClientAPI.Test.Model
{
    /// <summary>
    ///  Class for testing Bone
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BoneTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Bone
        //private Bone instance;

        public BoneTests()
        {
            // TODO uncomment below to create an instance of Bone
            //instance = new Bone();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Bone
        /// </summary>
        [Test]
        public void BoneInstanceTest()
        {
            // TODO uncomment below to test "IsType" Bone
            //Assert.IsType<Bone>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Matrix'
        /// </summary>
        [Test]
        public void MatrixTest()
        {
            // TODO unit test for the property 'Matrix'
        }
        /// <summary>
        /// Test the property 'Children'
        /// </summary>
        [Test]
        public void ChildrenTest()
        {
            // TODO unit test for the property 'Children'
        }
    }
}
