/*
 * Text2Motion API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Text2MotionClientAPI.Api;
using Text2MotionClientAPI.Model;
using Text2MotionClientAPI.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace Text2MotionClientAPI.Test.Model
{
    /// <summary>
    ///  Class for testing FeedbackRequestBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FeedbackRequestBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FeedbackRequestBody
        //private FeedbackRequestBody instance;

        public FeedbackRequestBodyTests()
        {
            // TODO uncomment below to create an instance of FeedbackRequestBody
            //instance = new FeedbackRequestBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FeedbackRequestBody
        /// </summary>
        [Test]
        public void FeedbackRequestBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" FeedbackRequestBody
            //Assert.IsType<FeedbackRequestBody>(instance);
        }

        /// <summary>
        /// Test the property 'RequestId'
        /// </summary>
        [Test]
        public void RequestIdTest()
        {
            // TODO unit test for the property 'RequestId'
        }
        /// <summary>
        /// Test the property 'Rating'
        /// </summary>
        [Test]
        public void RatingTest()
        {
            // TODO unit test for the property 'Rating'
        }
    }
}
