/*
 * Text2Motion API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Text2MotionClientAPI.Api;
using Text2MotionClientAPI.Model;
using Text2MotionClientAPI.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace Text2MotionClientAPI.Test.Model
{
    /// <summary>
    ///  Class for testing GenerateRequestBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GenerateRequestBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GenerateRequestBody
        //private GenerateRequestBody instance;

        public GenerateRequestBodyTests()
        {
            // TODO uncomment below to create an instance of GenerateRequestBody
            //instance = new GenerateRequestBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GenerateRequestBody
        /// </summary>
        [Test]
        public void GenerateRequestBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" GenerateRequestBody
            //Assert.IsType<GenerateRequestBody>(instance);
        }

        /// <summary>
        /// Test the property 'Prompt'
        /// </summary>
        [Test]
        public void PromptTest()
        {
            // TODO unit test for the property 'Prompt'
        }
        /// <summary>
        /// Test the property 'TargetSkeleton'
        /// </summary>
        [Test]
        public void TargetSkeletonTest()
        {
            // TODO unit test for the property 'TargetSkeleton'
        }
    }
}
