/*
 * Text2Motion API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Text2MotionClientAPI.Api;
using Text2MotionClientAPI.Model;
using Text2MotionClientAPI.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace Text2MotionClientAPI.Test.Model
{
    /// <summary>
    ///  Class for testing LocationInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LocationInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LocationInner
        //private LocationInner instance;

        public LocationInnerTests()
        {
            // TODO uncomment below to create an instance of LocationInner
            //instance = new LocationInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LocationInner
        /// </summary>
        [Test]
        public void LocationInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" LocationInner
            //Assert.IsType<LocationInner>(instance);
        }

    }
}
