/*
 * Text2Motion API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Text2MotionClientAPI.Api;
using Text2MotionClientAPI.Model;
using Text2MotionClientAPI.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace Text2MotionClientAPI.Test.Model
{
    /// <summary>
    ///  Class for testing Skeleton
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SkeletonTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Skeleton
        //private Skeleton instance;

        public SkeletonTests()
        {
            // TODO uncomment below to create an instance of Skeleton
            //instance = new Skeleton();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Skeleton
        /// </summary>
        [Test]
        public void SkeletonInstanceTest()
        {
            // TODO uncomment below to test "IsType" Skeleton
            //Assert.IsType<Skeleton>(instance);
        }

        /// <summary>
        /// Test the property 'WorldMatrix'
        /// </summary>
        [Test]
        public void WorldMatrixTest()
        {
            // TODO unit test for the property 'WorldMatrix'
        }
        /// <summary>
        /// Test the property 'Root'
        /// </summary>
        [Test]
        public void RootTest()
        {
            // TODO unit test for the property 'Root'
        }
    }
}
