/*
 * Text2Motion API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using NUnit.Framework;

using Text2MotionClientAPI.Client;
using Text2MotionClientAPI.Api;
// uncomment below to import models
//using Text2MotionClientAPI.Model;

namespace Text2MotionClientAPI.Test.Api
{
    /// <summary>
    ///  Class for testing FeedbackApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class FeedbackApiTests : IDisposable
    {
        private FeedbackApi instance;

        public FeedbackApiTests()
        {
            instance = new FeedbackApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FeedbackApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' FeedbackApi
            //Assert.IsType<FeedbackApi>(instance);
        }

        /// <summary>
        /// Test FeedbackApiFeedbackPost
        /// </summary>
        [Test]
        public void FeedbackApiFeedbackPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //FeedbackRequestBody feedbackRequestBody = null;
            //var response = instance.FeedbackApiFeedbackPost(feedbackRequestBody);
            //Assert.IsType<Object>(response);
        }
    }
}
