/*
 * Text2Motion API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Text2MotionClientAPI.Client.OpenAPIDateConverter;

namespace Text2MotionClientAPI.Model
{
    /// <summary>
    /// Request schema for Feedback API.
    /// </summary>
    [DataContract(Name = "FeedbackRequestBody")]
    public partial class FeedbackRequestBody
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FeedbackRequestBody" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FeedbackRequestBody() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FeedbackRequestBody" /> class.
        /// </summary>
        /// <param name="requestId">The request id of the generate request to provide feedback for. (required).</param>
        /// <param name="rating">The rating to give for the given request id, [1, 10]. (required).</param>
        public FeedbackRequestBody(string requestId = default(string), int rating = default(int))
        {
            // to ensure "requestId" is required (not null)
            if (requestId == null)
            {
                throw new ArgumentNullException("requestId is a required property for FeedbackRequestBody and cannot be null");
            }
            this.RequestId = requestId;
            this.Rating = rating;
        }

        /// <summary>
        /// The request id of the generate request to provide feedback for.
        /// </summary>
        /// <value>The request id of the generate request to provide feedback for.</value>
        [DataMember(Name = "request_id", IsRequired = true, EmitDefaultValue = true)]
        public string RequestId { get; set; }

        /// <summary>
        /// The rating to give for the given request id, [1, 10].
        /// </summary>
        /// <value>The rating to give for the given request id, [1, 10].</value>
        [DataMember(Name = "rating", IsRequired = true, EmitDefaultValue = true)]
        public int Rating { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FeedbackRequestBody {\n");
            sb.Append("  RequestId: ").Append(RequestId).Append("\n");
            sb.Append("  Rating: ").Append(Rating).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
